### ISSUE TITLE
flooding log if host is unreachable

### ISSUE THREAD

**Issue by rollercontainer** [mwittig/pimatic-yamaha-avr#2]
If the AVR isnt powered, the log file of pimatic 0.9 is flooded with an error. This shouldn't be, I think. Absent means off, and that should be stated.
Error:
error [pimatic-yamaha-avr]: [Plugin] Error: { [Error: connect EHOSTUNREACH 192.xxx.xxx.xxx:80]
  code: 'EHOSTUNREACH',
  errno: 'EHOSTUNREACH',
  syscall: 'connect',
  address: '192.xxx.xxx.xxx',
  port: 80,
  __trace: 'Error: From connect\n    at Socket.connect (/home/pi/pimatic-app/node_modules/pimatic/startup.coffee:55:29)\n    at Agent.exports.connect.exports.createConnection (net.js:69:26)\n    at Agent.createSocket (_http_agent.js:180:16)\n    at Agent.addRequest (_http_agent.js:149:23)\n    at new ClientRequest (_http_client.js:142:16)\n    at Object.exports.request (http.js:31:10)\n    at new Request (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/node_modules/restler-promise/node_modules/restler-base/lib/restler.js:75:24)\n    at request (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/node_modules/restler-promise/node_modules/restler-base/lib/restler.js:327:17)\n    at Object.post (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/node_modules/restler-promise/node_modules/restler-base/lib/restler.js:342:10)\n    at /home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/node_modules/restler-promise/lib/restler-promise.js:28:38\n    at Promise._execute (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/debuggability.js:272:9)\n    at Promise._resolveFromExecutor (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:475:18)\n    at new Promise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:77:14)\n    at Object.post (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/node_modules/restler-promise/lib/restler-promise.js:27:20)\n    at /home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/yamaha-avr.coffee:97:14\n    at Promise._execute (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/debuggability.js:272:9)\n    at Promise._resolveFromExecutor (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:475:18)\n    at new Promise (/home/pi/pimatic-app/node_modules/pimatic/node_modules/bluebird/js/release/promise.js:77:14)\n    at YamahaAvrPlugin.sendRequest (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/yamaha-avr.coffee:95:18)\n    at YamahaAvrPlugin._requestStatusUpdates (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/yamaha-avr.coffee:73:10)\n    at [object Object]._onTimeout (/home/pi/pimatic-app/node_modules/pimatic-yamaha-avr/node_modules/pimatic-plugin-commons/lib/index.js:218:27)\n    at Timer.listOnTimeout (timers.js:92:15)' }

**Comment by mwittig** [comment]
Do you have the property `"debug"` enabled for the "yamaha-avr" plugin? If you set `"debug"` to `false`, the error message should only occur once! Please let me know if this works for you.

#### Contributions

Contributions to the project are  welcome. You can simply fork the project and create a pull request with 
your contribution to start with. If you like this plugin, please consider &#x2605; starring 
[the project on github](https://github.com/mwittig/pimatic-yamaha-avr).

**Comment by rollercontainer** [comment]
You are right, my fault.
