### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by ccvh** [mwittig/pimatic-yamaha-avr#5]
Hey,

i get the following message once after every startup of pimatic:
error [pimatic]: Could not initialize the plugin "yamaha-avr": Cannot find module './actions/yamaha-avr-input-select-action'

The plugin itself works without any issues.

**Comment by mwittig** [comment]
Ooops, sorry. Fixed in pimatic-yamaha-avr@0.9.3. It may take a few minutes before the update becomes accessible via the mobile-frontend.

Thanks for reporting
